# Generated by Django 4.2.5 on 2023-10-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='book_reviewed',
            new_name='book_asked',
        ),
    ]
