# Generated by Django 4.2.6 on 2023-10-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_katalog_bookauthor_alter_katalog_booktitle_and_more'),
        ('authentication', '0002_userprofile_owned_books_alter_userprofile_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tracker',
            field=models.ManyToManyField(related_name='tracker', to='products.katalog'),
        ),
    ]
