# Generated by Django 4.2.6 on 2023-10-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_nama_buku_booktracker_judul_and_more'),
        ('authentication', '0003_userprofile_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tracker',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tracked_books',
            field=models.ManyToManyField(related_name='tracked_books', to='tracker.booktracker'),
        ),
    ]
