# Generated by Django 4.2.6 on 2023-10-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_katalog_bookauthor_alter_katalog_booktitle_and_more'),
        ('cart', '0002_history_buku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='buku',
        ),
        migrations.AddField(
            model_name='history',
            name='buku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.katalog'),
        ),
    ]
