# Generated by Django 4.2.6 on 2023-10-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktracker',
            old_name='nama_buku',
            new_name='judul',
        ),
        migrations.AlterField(
            model_name='booktracker',
            name='halaman_terakhir',
            field=models.IntegerField(),
        ),
    ]
