# Generated by Django 4.2.6 on 2023-10-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_nama_buku_booktracker_judul_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktracker',
            old_name='judul',
            new_name='nama_buku',
        ),
    ]
