# Generated by Django 4.2.6 on 2023-10-28 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_judul_booktracker_nama_buku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktracker',
            old_name='nama_buku',
            new_name='judul',
        ),
    ]
