# Generated by Django 4.2.6 on 2023-10-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_booktracker_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktracker',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
