# Generated by Django 4.2.6 on 2023-10-29 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_katalog_bookauthor_alter_katalog_booktitle_and_more'),
        ('tracker', '0007_alter_booktracker_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktracker',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.katalog'),
        ),
    ]
