# Generated by Django 4.2.6 on 2023-12-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_booktracker_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktracker',
            old_name='judul',
            new_name='book_title',
        ),
        migrations.RenameField(
            model_name='booktracker',
            old_name='halaman_terakhir',
            new_name='last_page',
        ),
        migrations.RenameField(
            model_name='booktracker',
            old_name='tanggal',
            new_name='last_read_timestamp',
        ),
    ]
