# Generated by Django 4.2.4 on 2023-10-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=20, verbose_name='ISBN')),
                ('BookTitle', models.CharField(max_length=100, verbose_name='Book-Title')),
                ('BookAuthor', models.CharField(max_length=100, verbose_name='Book-Author')),
                ('Publisher', models.CharField(max_length=100, verbose_name='Publisher')),
                ('Year_Of_Publication', models.IntegerField(verbose_name='Year-Of-Publication')),
                ('Image', models.ImageField(upload_to='', verbose_name='Image-URL-M')),
            ],
        ),
    ]
