# Generated by Django 4.2.4 on 2023-10-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='BookAuthor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='BookTitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='ISBN',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='Image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='Publisher',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='Year_Of_Publication',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
