# Generated by Django 4.2.4 on 2023-10-29 05:51

from django.db import migrations
from django.core.management import call_command


class Migration(migrations.Migration):
    def load_my_initial_data(apps, schema_editor):
        call_command("loaddata", "data.json")

    dependencies = [
        ('products', '0002_alter_katalog_bookauthor_alter_katalog_booktitle_and_more'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
    

